CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) DEFAULT '',
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  username VARCHAR(255) DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  is_member TINYINT(1) NOT NULL DEFAULT 0,
  verified_at DATETIME DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS trivia_leaderboard (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT DEFAULT NULL,
  name VARCHAR(255) NOT NULL,
  score INT NOT NULL,
  total INT NOT NULL DEFAULT 100,
  percentage INT NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS events (
  id VARCHAR(50) PRIMARY KEY,
  title VARCHAR(255) NOT NULL DEFAULT '',
  date VARCHAR(50) DEFAULT '',
  time VARCHAR(50) DEFAULT '',
  location VARCHAR(255) DEFAULT '',
  status VARCHAR(50) DEFAULT 'upcoming',
  duration DECIMAL(3,1) DEFAULT 2,
  description TEXT DEFAULT NULL,
  image VARCHAR(500) DEFAULT '',
  homepage TINYINT(1) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS gallery (
  id VARCHAR(50) PRIMARY KEY,
  title VARCHAR(255) NOT NULL DEFAULT '',
  meta VARCHAR(255) DEFAULT '',
  images TEXT,
  homepage TINYINT(1) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS spotlight (
  id VARCHAR(50) PRIMARY KEY,
  type VARCHAR(50) DEFAULT '',
  event VARCHAR(255) DEFAULT '',
  date VARCHAR(50) DEFAULT '',
  title VARCHAR(255) DEFAULT '',
  subtitle VARCHAR(255) DEFAULT '',
  image VARCHAR(500) DEFAULT '',
  homepage TINYINT(1) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sports (
  id VARCHAR(50) PRIMARY KEY,
  sport VARCHAR(50) DEFAULT 'football',
  competition VARCHAR(255) DEFAULT '',
  date VARCHAR(50) DEFAULT '',
  team1 VARCHAR(255) DEFAULT '',
  team2 VARCHAR(255) DEFAULT '',
  score1 INT DEFAULT 0,
  score2 INT DEFAULT 0,
  notes TEXT DEFAULT NULL,
  notes2 TEXT DEFAULT NULL,
  homepage TINYINT(1) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS kv_store (
  `key` VARCHAR(100) PRIMARY KEY,
  `value` TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rsvps (
  id INT AUTO_INCREMENT PRIMARY KEY,
  event_id VARCHAR(50) NOT NULL,
  event_title VARCHAR(255) DEFAULT '',
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS leadership (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(255) NOT NULL DEFAULT '',
  role VARCHAR(255) DEFAULT '',
  initials VARCHAR(20) DEFAULT '',
  color VARCHAR(20) DEFAULT '',
  img VARCHAR(500) DEFAULT '',
  quote TEXT
);

CREATE TABLE IF NOT EXISTS families (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(255) NOT NULL DEFAULT '',
  sub VARCHAR(255) DEFAULT '',
  color VARCHAR(20) DEFAULT '',
  members TEXT
);

CREATE TABLE IF NOT EXISTS programs (
  id VARCHAR(50) PRIMARY KEY,
  title VARCHAR(255) NOT NULL DEFAULT '',
  `desc` TEXT,
  meta TEXT
);

CREATE TABLE IF NOT EXISTS hof (
  id VARCHAR(50) PRIMARY KEY,
  icon VARCHAR(50) DEFAULT '',
  year VARCHAR(20) DEFAULT '',
  title VARCHAR(255) DEFAULT '',
  `desc` TEXT
);

CREATE TABLE IF NOT EXISTS football_squad (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(255) NOT NULL DEFAULT '',
  num INT DEFAULT 0,
  label VARCHAR(255) DEFAULT '',
  `group` VARCHAR(100) DEFAULT '',
  x INT DEFAULT 50,
  y INT DEFAULT 50,
  color VARCHAR(20) DEFAULT '',
  img VARCHAR(500) DEFAULT '',
  position VARCHAR(100) DEFAULT '',
  rating INT DEFAULT 50,
  stats TEXT
);

CREATE TABLE IF NOT EXISTS santa_interests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(50) UNIQUE NOT NULL,
  label VARCHAR(100) NOT NULL,
  category VARCHAR(50) DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS youth_members (
  id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS verification_codes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  code VARCHAR(10) NOT NULL,
  expires_at DATETIME NOT NULL,
  used TINYINT(1) NOT NULL DEFAULT 0,
  attempts INT NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  KEY idx_user (user_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS santa_profiles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNIQUE NOT NULL,
  username VARCHAR(255) DEFAULT NULL,
  interests JSON,
  description TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS santa_matches (
  id INT AUTO_INCREMENT PRIMARY KEY,
  santa_user_id INT NOT NULL,
  recipient_user_id INT NOT NULL,
  matched_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (santa_user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (recipient_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


